# Example of a configuration yaml file.

# Data
save_data: data/dataset
src_vocab: data/dataset/src.vocab
tgt_vocab: data/dataset/tgt.vocab
overwrite: False

# Corpora:
data:
    corpus_1:
        path_src: data/dataset/tr.src
        path_tgt: data/dataset/tr.tgt
    valid:
        path_src: data/dataset/dev.src
        path_tgt: data/dataset/dev.tgt
# Model
decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
hidden_size: 512
layers: 6
transformer_ff: 2048
heads: 8
accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1
max_generator_batches: 2
param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

# Train on a single GPU
world_size: 1
gpu_ranks:
  - 0

# Checkpoints
save_model: data/models/model
save_checkpoint_steps: 1000
train_steps: 100000
valid_steps: 1000
keep_checkpoint: 10
seed: 3435
report_every: 100
